[tool.poetry]
name = "edgeimpulse"
version = "1.0.6"
description = "Python SDK for Edge Impulse."
authors = ["EdgeImpulse Inc. <hello@edgeimpulse.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://edgeimpulse.com"
documentation = "https://docs.edgeimpulse.com/docs/edge-impulse-python-sdk/overview"
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Embedded Systems"
]

[tool.poetry.dependencies]
python = "^3.8"
#edgeimpulse-api = {path = "../../api-bindings/python/library", develop = true}
edgeimpulse-api = "1.29.20"

[tool.poetry.dev-dependencies]
numpy = "^1.22"
onnx = "^1.12"
sphinx = "7.1.2"
furo = "2023.7.26"
myst-parser = "2.0.0"
m2r2 = "0.3.3.post2"
pyYAML = "6.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pypi-test"
url = "https://test.pypi.org/simple"
secondary = true
