[tool.poetry]
name = "edgeimpulse"
version = "1.0.5"
description = "Python SDK for Edge Impulse."
authors = ["EdgeImpulse Inc. <hello@edgeimpulse.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://edgeimpulse.com"
documentation = "https://docs.edgeimpulse.com/docs/edge-impulse-python-sdk/overview"
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Embedded Systems"
]

[tool.poetry.dependencies]
python = "^3.8"
edgeimpulse-api = {path = "../api-bindings/python/library", develop = true}

[tool.poetry.dev-dependencies]
numpy = "^1.22"
onnx = "^1.12"
sphinx = "5.3.0"
sphinx-markdown-builder = "0.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pypi-test"
url = "https://test.pypi.org/simple"
secondary = true
